export const ADD_PROJECT = 'ADD_PROJECT';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT';
export const ADD_TASK = 'ADD_TASK';
export const SET_CURRENT_TASK = 'SET_CURRENT_TASK';
